# Generated by Django 6.0.6 on 2026-06-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_receipt_user_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='qr_url',
            field=models.URLField(blank=True, max_length=512),
        ),
    ]
