# Generated by Django 6.0.6 on 2026-06-05 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0004_pendingimport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(condition=models.Q(('fn__gt', ''), ('check_id__gt', '')), fields=('user', 'fn', 'check_id'), name='unique_receipt_per_user'),
        ),
    ]
